name: Build Images

on:
  push:
    branches: master
  pull_request:
    paths:
      - docker-compose.yml
      - services
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - invoke
          - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: docker compose --profile ${{ matrix.profile }} build --progress plain

      - name: Push images
        run: docker compose --profile ${{ matrix.profile }} push
